// <auto-generated />
namespace NbuBookLibrary.BooksMigrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class initBooks : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(initBooks));
        
        string IMigrationMetadata.Id
        {
            get { return "201705270718376_initBooks"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
